TERMUX_PKG_HOMEPAGE=https://www.libraw.org
TERMUX_PKG_DESCRIPTION="The LibRaw library provides a simple and unified interface for extracting out of RAW files generated by digital photo cameras."
TERMUX_PKG_LICENSE="GPL-2.1, CDDL-1.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.20.2
TERMUX_PKG_SRCURL=https://www.libraw.org/data/LibRaw-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=dc1b486c2003435733043e4e05273477326e51c3ea554c6864a4eafaff1004a6
TERMUX_PKG_DEPENDS="libjasper, zlib"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_pre_configure() {
	sed -i 's/1.15/1.16/g' configure
}
